#!/bin/bash

if [ "$1-" == "-" ]; then
   echo "fastqc2tsv fastqc.zip"
   exit 1
fi
zip=y
ifile=$1
cat_cmd="unzip -p $ifile"
if [ ! -e $ifile ] ; then
   echo "$ifile not found"  1>&2
   zip=n	
   ifile=`echo $ifile|sed "s/.fastqc.zip/_fastqc/"`
   if [ ! -e $ifile ] ; then 
      echo "$ifile not found"  1>&2	
      exit 1
   fi   
   cat_cmd=cat		
fi
pref=`basename $ifile|sed "s/.fastqc.zip//"|sed "s/_fastqc//"`
echo "FASTQC $pref" | tr " " "\t"
$cat_cmd  ${pref}_fastqc/summary.txt | awk  -F"\t"  '{print $2"\t"$1}'
$cat_cmd  ${pref}_fastqc/fastqc_data.txt  | grep "Total Sequences" 

exit 0

# example: fasqc2tsv test3/report/riq/raw_data/SE1.f.fastqc.zip
# example: fasqc2tsv test3/report/riq/raw_data/SE1.f_fastqc
