#!/usr/bin/env bash
# =========================================================
# Copyright 2012-2018,  Nuno A. Fonseca (nuno dot fonseca at gmail dot com)
#
# This file is part of iRAP.
#
# This is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with iRAP.  If not, see <http://www.gnu.org/licenses/>.
#
#
#    $Id: 0.1.1$
# =========================================================
#Send irap jobs on the farm - if paired end files, parallelize
#Input: a config file and path to directory containing fastq files
#Output: send jobs on the farm
#A README file (fastq_qc_README.txt) with more details about each step and 
# the general process is available in the same directory.

set -e 

###################################
# load shared code
LSF_CMD=irap_stage3_lsf
source $IRAP_DIR/aux/sh/irap_fun.sh
source $IRAP_DIR/aux/sh/lsf_shared_code.sh

################
# length of jobname needs to be small otherwise lsf dependencies will not work
declare -i s1=0
declare -i s2=0


wf1=`irap_init_job|tail -n 1`
wf2=`stage0_jobs $wf1|tail -n 1`
wf3=`stage123_jobs $wf2|tail -n 1`
IRAP_PARAMS="$IRAP_PARAMS stage3"
final_job $wf3 $wf1
exit
