#!/bin/bash
# resort the SQ entries in the header of a BAM file
if [  "$1-" == "-" ]; then
   echo "Usage: irap_bam_fixSQ_order bam_filename out_bam" 
   exit 1
fi

if [ ! -e  $1 ] ; then
   echo "$1 not found"
   exit 1
fi

set -e 
# get the current header
samtools view -H $1 | grep "@SQ" > $1.seq.order.sam
sort -k 2,2 $1.seq.order.sam > $1.seq.neworder.sam
set +e
diff $1.seq.neworder.sam $1.seq.order.sam > /dev/null
DIFF=$?
set -e
if [ $DIFF -eq 0 ]; then
    #same order
    echo "No reordering of @SQ entries required in BAM file $1"
    cp $1 $2.tmp && mv $2.tmp $2
else
    echo "Reordering @SQ entries in BAM file $1"
    samtools view -H $1 | grep -v "^@SQ" > $1.header.sam
    cat $1.seq.neworder.sam >> $1.header.sam
    ( cat $1.header.sam; samtools view $1 ) | samtools view -b  - > $2.tmp && mv $2.tmp $2
    echo "Reordering @SQ entries in BAM file $1...done"
fi
# samtools reheader -P $1.header.sam $1 > $2
#rm -f $1.header $1.seq.neworder.sam $1.seq.order.sam
exit 0
