#!/usr/bin/env Rscript
# =========================================================
#
# This file is part of iRAP.
#
# This is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with iRAP.  If not, see <http://www.gnu.org/licenses/>.
#
#
#    $Id: irap.txt Nuno Fonseca Tue Jan 29 23:13:16 2013$
# =========================================================

###############################################################
suppressPackageStartupMessages(library("optparse"))

IRAP.DIR <- Sys.getenv(c("IRAP_DIR"))
if ( IRAP.DIR == "" ) {
  cat("ERROR: environment variable IRAP_DIR is not set\n")
  q(status=1)
}

# specify our desired options in a list
#
source(paste(IRAP.DIR,"aux/R","irap_utils.R",sep="/"))
source(paste(IRAP.DIR,"aux/R","irap_de.R",sep="/"))

cmd <- "irap_DE_voom"
pwarning("VOOM support: Under development!!!!!!!")


opt <- process.cmdline.args(cmd)
pinfo("Parameters parsed.")

if ( length(opt$labels.v) > 2 ) {
  perror("irap_DE_voom only supports pairwise comparisons!");
  q(status=2);
}

system(paste("mkdir -p ",opt$out));
data <- quant.load(opt$tsv_file)
## debug
pdebug.save.state("irap_DE_voom","1")
data.f <- filter.read.counts.table(data,opt)
data.f <- handle.tech.replicates(data.f,opt)
opt$conds <- map.conds2cols(opt$label2group,colnames(data.f))
#########################
library(limma)
#Note: TODO counts of technical replicates  have to be summed up into a single column
#conds.f <- factor(conds)
design <- model.matrix(~ 0 + opt$conds)
colnames(design) <- gsub("opt.conds", "", colnames(design)) #fix col names
# reorder
design <- design[,opt$labels.v]
pinfo("Vooming...")
voom.cts <- voom(data.f, design = design)

#Linear model fitting and differential expression analysis. Fit linear models to genes and assess differential expression using the eBayes moderated t statistic.
fit <- eBayes(lmFit(voom.cts,design))

de <- topTable(fit,number=nrow(fit))

# add fold change
label1.i <- 2
label2.i <- 3
de$foldChange <- de[,label2.i]/de[,label1.i]
de$log2FoldChange <- log2(de$foldChange)

pinfo("Annotating DE list...")
## annotate the gene list
if (!is.null(opt$annotation) && !is.null(opt$annotation)) {
   de.annot <- de
   match.v  <- match(de.annot$ID,opt$annot[opt$annot[,1] %in% de.annot$ID,1]);
   de.annot <- cbind(de.annot,opt$annot[match.v,])
} else {
   de.annot <- de;
}
de.annot <- de.annot[order(de.annot$P.Value),];

# save DE file
save.de2tsv(de.annot,ofile.prefix=opt$out)
# save the objects
save(opt,de.annot,design,voom.cts,data,data.f,file=paste(opt$out,"de.Rdata",sep="/"))
quit(save="no",status=0)

######################################
irap_DE_voom_debug <- function(rdata.obj) {
  load(rdata.obj,envir=.GlobalEnv)
  pdebug.rdata()
  source(paste(IRAP.DIR,"aux/R","irap_utils.R",sep="/"))
  library(limma)
}
IRAP.DIR=getwd()
Sys.setenv(IRAP_DIR=IRAP.DIR)
rdata.obj="irap_DE_voom.Rdata"
irap_DE_voom_debug("irap_DE_voom.Rdata")
