#!/bin/sh
#; -*- mode: Makefile;-*-
#the next line restarts using\
exec make --warn-undefined-variables -Rf "$0"  ${1+"$@"} 
###############################################
file_exists=$(if  $(realpath $(1)),,$(call error,$(1) not found))

ifdef bam
 $(call file_exists,$(bam))
else
 $(call error,Missing bam parameter)
endif


all: $(bam).stats.csv

# index the bam
%.bam.ridx: %.bam
	bamRindex $< $@.tmp && mv $@.tmp.ridx $@

# Perform the queries
%.bam.stats.csv: %.bam.ridx
	@irapBAM2stats.sh $*.bam | sed "s/ = /,/" > $@.tmp && mv $@.tmp $@ && \
	echo "File $@ created successfully."
