#!/bin/sh
#; -*- mode: Makefile;-*-
#the next line restarts using\
exec make --warn-undefined-variables -Rf "$0"  ${1+"$@"} 
###############################################
# =========================================================
# Copyright 2012-2018,  Nuno A. Fonseca (nuno dot fonseca at gmail dot com)
#
# This file is part of iRAP.
#
# This is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with iRAP.  If not, see <http://www.gnu.org/licenses/>.
#
#
# =========================================================
file_exists=$(if  $(realpath $(1)),,$(call error,$(1) not found))

ifdef bam
 $(call file_exists,$(bam))
else
 $(call error,Missing bam parameter)
endif


all: $(bam).stats.csv

# index the bam
%.bam.ridx: %.bam
	bamRindex $< $@.tmp && mv $@.tmp.ridx $@

# Perform the queries
%.bam.stats.csv: %.bam.ridx
	set -o pipefail && irapBAM2stats.sh $*.bam | sed "s/ = /,/" > $@.tmp && mv $@.tmp $@ && \
	echo "File $@ created successfully."
