#!/usr/bin/env bash

if [ "$1-" == "-" ]; then
   echo "irap_fastqc2tsv fastqc.zip"
   exit 1
fi


set -e 


zip=y
ifile=$1
cat_cmd="unzip -p $ifile"
if [ ! -e $ifile ] ; then
   echo "WARNING: $ifile not found" > /dev/stderr
   zip=n	
   ifile=`echo $ifile|sed "s/.fastqc.zip/_fastqc/"`
   if [ ! -e $ifile ] ; then 
       echo "ERROR: $ifile not found" > /dev/stderr	
      exit 1
   fi   
   cat_cmd=cat
else
    unzip -t $1 > /dev/stderr
fi
pref=`basename $ifile|sed "s/.fastqc.zip//"|sed "s/_fastqc//"`
echo "FASTQC $pref" | tr " " "\t"
$cat_cmd  ${pref}_fastqc/summary.txt | awk  -F"\t"  '{print $2"\t"$1}'
$cat_cmd  ${pref}_fastqc/fastqc_data.txt  | grep "Total Sequences" | sed 's/\t$//'
$cat_cmd  ${pref}_fastqc/fastqc_data.txt  | grep "Basic Statistics" | sed 's/\t$//' | sed "s/>>/FASTQC /"
$cat_cmd  ${pref}_fastqc/fastqc_data.txt  | grep "%GC" | sed 's/\t$//'|sed 's/^%//'

exit 0
