#!/bin/env perl 

use strict;


if ($ARGV[0] eq "")  {
	    print "ERROR: Usage irap_check_gtf gtf_file\n";
	    exit(1);
}

my $FEATURES=`cut -f 3 $ARGV[0]|sort -u`;
$FEATURES=~s/\n/ /g;
print "Features found: $FEATURES\n";
my @features=split(" ",$FEATURES);
# Mandatory features
my @must_have=("exon","CDS","start_codon","stop_codon");

foreach my $feat (@must_have) {
    if ( grep(/$feat/,@features)==0 ) {
	    print "ERROR: Feature $feat not found\n";
	    exit(2);
    }
}

if ( scalar(@features) > scalar(@must_have) )  {
	print "WARNING: File contains not mandatory features,  some programs may fail.\n";
	exit;
}

print "File '$ARGV[0]' looks ok.\n";
exit(0);