#!/usr/bin/env bash

if [ "$1-" == "-" ]; then
   echo "irap_fastqc2tsv fastqc.zip"
   exit 1
fi


set -eu
set -o pipefail 

zip=y
ifile=$1
cat_cmd="unzip -p $ifile"
if [ ! -e $ifile ] ; then
   echo "WARNING: $ifile not found"  1>&2
   zip=n	
   ifile=`echo $ifile|sed "s/.fastqc.zip/_fastqc/"`
   if [ ! -e $ifile ] ; then 
       echo "ERROR: $ifile not found"  1>&2	
      exit 1
   fi   
   cat_cmd=cat
else
    unzip -t $1  1>&2
fi
pref=`basename $ifile|sed "s/.fastqc.zip//"|sed "s/_fastqc//"`
echo "FASTQC $pref" | tr " " "\t"

$cat_cmd  ${pref}_fastqc/summary.txt | grep -m 1 "Basic Statistics" | awk  -F"\t"  '{print $2"\t"$1}'
$cat_cmd  ${pref}_fastqc/summary.txt | grep -m 1  "Per base sequence quality" | awk  -F"\t"  '{print $2"\t"$1}'
$cat_cmd  ${pref}_fastqc/summary.txt | grep -m 1  "Per sequence quality scores" | awk  -F"\t"  '{print $2"\t"$1}'
$cat_cmd  ${pref}_fastqc/summary.txt | grep -m 1  "Per base sequence content" | awk  -F"\t"  '{print $2"\t"$1}'
$cat_cmd  ${pref}_fastqc/summary.txt | grep -m 1  "Per sequence GC content" | awk  -F"\t"  '{print $2"\t"$1}'
$cat_cmd  ${pref}_fastqc/summary.txt | grep -m 1  "Per base N content" | awk  -F"\t"  '{print $2"\t"$1}'
$cat_cmd  ${pref}_fastqc/summary.txt | grep  -m 1 "Sequence Length Distribution" | awk  -F"\t"  '{print $2"\t"$1}'
$cat_cmd  ${pref}_fastqc/summary.txt | grep  -m 1 "Sequence Duplication Levels" | awk  -F"\t"  '{print $2"\t"$1}'
$cat_cmd  ${pref}_fastqc/summary.txt | grep  -m 1 "Overrepresented sequences" | awk  -F"\t"  '{print $2"\t"$1}'
$cat_cmd  ${pref}_fastqc/summary.txt | grep  -m 1 "Adapter Content" | awk  -F"\t"  '{print $2"\t"$1}'
set +e
$cat_cmd  ${pref}_fastqc/fastqc_data.txt  | grep  -m 1 "Total Sequences" | sed 's/\t$//'
$cat_cmd  ${pref}_fastqc/fastqc_data.txt  | grep  -m 1 "Basic Statistics" | sed 's/\t$//;s/>>/FASTQC /'
$cat_cmd  ${pref}_fastqc/fastqc_data.txt  | grep  -m 1 "%GC" | sed 's/\t$//;s/^%//'

exit 0
