#!/usr/bin/env Rscript
# =========================================================
#
# This file is part of iRAP.
#
# This is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with iRAP.  If not, see <http://www.gnu.org/licenses/>.
#
#
#    $Id: 0.1.1$
# =========================================================
IRAP.DIR <- Sys.getenv(c("IRAP_DIR"))
if ( IRAP.DIR == "" ) {
  cat("ERROR: environment variable IRAP_DIR is not set\n")
  q(status=1)
}

source(paste(IRAP.DIR,"aux/R","irap_utils.R",sep="/"))
pdebug.enabled <- TRUE


args <- commandArgs(trailingOnly=TRUE)

tsv.file <- args[1]
gtf.file<- args[2]
out.file <- args[3]

# TODO validate arguments
if ( is.na(out.file)) {
  cat("ERROR!\n usage: tsvAggrTransByGene TSVfile gtf outfile\n")
  q(status=1) 		
} 

# read matrix (TSV)
tsv.mat<-read.table(tsv.file,sep="\t",header=F)

# read gtf file
gtf.mat <- load.gtf(gtf.file,feature="CDS",selected.attr=c("gene_id","transcript_id"))

# remove duplicate entries (due to exons)
gtf.mat.u <- gtf.mat[!duplicated(gtf.mat$transcript_id),c("gene_id","transcript_id")]

# merge the two matrices
new.mat<-merge(tsv.mat,gtf.mat.u,by.x=colnames(tsv.mat)[1],by.y="transcript_id",all.x=TRUE,sort=F)

# aggregate!
cols2aggr <- colnames(new.mat)[! colnames(new.mat) %in% c(colnames(new.mat)[1],"gene_id","transcript_id")]
a<-aggregate(new.mat[,cols2aggr], by=list(gene_id=new.mat$gene_id), "sum")

# save file
df <- data.frame(a)
df <- df[,append("gene_id",cols2aggr)]
#colnames(df) <- append("GENE",cols2aggr)
write.table(df[,c("gene_id",cols2aggr)],file=out.file,row.names=F,sep="\t",quote=FALSE,col.names=T)
  
q(status=0)
tsvAgrrTransByGene transcripts.mol.true.tsv ../../../test_data/test_annot.gtf x




